[build]
publish = "public"
command = "hugo"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.55.1"
  HUGO_ENV = "dev"

[context.production.environment]
  HUGO_VERSION="0.55.1"
  HUGO_ENV = "production"
